# Generated by Django 5.2.4 on 2025-07-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('numero_identificacao', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('FUNCIONARIO', 'Funcionário'), ('COORDENADOR', 'Coordenador'), ('DIRETOR', 'Diretor')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
            ],
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('siape', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
            ],
            bases=('app.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade'),
        ),
        migrations.CreateModel(
            name='HistoricoConduta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ocorrencias', models.IntegerField(default=0)),
                ('ultimas_ocorrencias', models.TextField(blank=True)),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='InstituicaoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('site', models.URLField(blank=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('carga_horaria_total', models.IntegerField()),
                ('duracao_meses', models.IntegerField()),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ocupacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ocupacao'),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('anonima', models.BooleanField(default=False)),
                ('email_denunciante', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_agressor', models.CharField(max_length=100)),
                ('curso_agressor', models.CharField(blank=True, max_length=100, null=True)),
                ('turma_agressor', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_vitima', models.CharField(max_length=100)),
                ('curso_vitima', models.CharField(blank=True, max_length=100, null=True)),
                ('turma_vitima', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_ocorrencia', models.CharField(choices=[('agressao_fisica', 'Agressão física'), ('agressao_verbal', 'Agressão verbal'), ('bullying', 'Bullying'), ('cyberbullying', 'Cyberbullying'), ('psicologica', 'Violência psicológica'), ('ameaca', 'Ameaça'), ('discriminacao', 'Discriminação'), ('assedio_moral', 'Assédio moral'), ('assedio_sexual', 'Assédio sexual'), ('furto_roubo', 'Furto / roubo'), ('dano_patrimonio', 'Dano ao patrimônio'), ('porte_arma', 'Porte de arma'), ('uso_drogas', 'Uso de substância ilícita'), ('venda_drogas', 'Venda de substância ilícita'), ('violencia_domestica', 'Violência doméstica'), ('autolesao', 'Autolesão / tentativa de suicídio'), ('outros', 'Outros')], max_length=30)),
                ('pessoa_denunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='app.pessoa')),
                ('ocupacao_agressor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_agressor', to='app.ocupacao')),
                ('ocupacao_vitima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_vitima', to='app.ocupacao')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_faltas', models.IntegerField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_previsao_termino', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turma')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aluno')),
            ],
        ),
    ]
